%YAML:1.0

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 1000
num_features_init: 50
num_features_tracking: 50

loop_closure_kf_queue_max_size: 100

# topics
cam0_topic: "cam0"
cam1_topic: "cam1"


